services:
    3xui:
        image: ghcr.io/mhsanaei/3x-ui:latest
        container_name: 3xui_app
        volumes:
            - $PWD/db/:/etc/x-ui/
            - $PWD/cert/:/root/cert/
        labels:
            traefik.enable: "true"

            traefik.http.routers.xui-http.rule: Host(`${PANEL_HOST}`)
            traefik.http.routers.xui-http.entrypoints: web
            traefik.http.routers.xui-http.middlewares: xui-https-redirect
            traefik.http.middlewares.xui-https-redirect.redirectscheme.scheme: https

            traefik.http.routers.xui-https.rule: Host(`${PANEL_HOST}`)
            traefik.http.routers.xui-https.entrypoints: websecure
            traefik.http.routers.xui-https.tls: "true"
            traefik.http.routers.xui-https.tls.certresolver: le
            traefik.http.routers.xui-https.service: xui-panel
            traefik.http.services.xui-panel.loadbalancer.server.port: "${PANEL_PORT}"

            traefik.http.routers.xui-sub-http.rule: Host(`${SUBSCRIPTION_HOST}`)
            traefik.http.routers.xui-sub-http.entrypoints: web
            traefik.http.routers.xui-sub-http.middlewares: xui-https-redirect

            traefik.http.routers.xui-sub-https.rule: Host(`${SUBSCRIPTION_HOST}`)
            traefik.http.routers.xui-sub-https.entrypoints: websecure
            traefik.http.routers.xui-sub-https.tls: "true"
            traefik.http.routers.xui-sub-https.tls.certresolver: le
            traefik.http.routers.xui-sub-https.service: xui-sub
            traefik.http.services.xui-sub.loadbalancer.server.port: "${SUBSCRIPTION_PORT}"

            traefik.docker.network: proxy
        tty: true
        ports:
            - "8443:8443"
        networks:
            - default
            - proxy
        restart: unless-stopped

networks:
    proxy:
        external: true
